//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThunderCross {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThunderCross.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string browse {
            get {
                return ResourceManager.GetString("browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Thunder Error!
        ///Please verify ThunderAgent.dll is registed correctly!.
        /// </summary>
        public static string Call_Thunder_Error_Agent {
            get {
                return ResourceManager.GetString("Call_Thunder_Error_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThunderCross.json.
        /// </summary>
        public static string Config_json {
            get {
                return ResourceManager.GetString("Config_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this automatically for files like this from now on..
        /// </summary>
        public static string Do_this_automatically_for_files_like_this_from_now_on {
            get {
                return ResourceManager.GetString("Do_this_automatically_for_files_like_this_from_now_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download in Firefox.
        /// </summary>
        public static string Download_in_Firefox {
            get {
                return ResourceManager.GetString("Download_in_Firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download using .
        /// </summary>
        public static string Download_using_ {
            get {
                return ResourceManager.GetString("Download_using_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Thunder.
        /// </summary>
        public static string Fixing {
            get {
                return ResourceManager.GetString("Fixing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: .
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install fail. Please check whether Firefox is installed properly..
        /// </summary>
        public static string Install_fail {
            get {
                return ResourceManager.GetString("Install_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for.
        /// </summary>
        public static string Only_for {
            get {
                return ResourceManager.GetString("Only_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This copy of Thunder supports 32-bit only..
        /// </summary>
        public static string This_copy_of_Thunder_supports_32_bit_only {
            get {
                return ResourceManager.GetString("This_copy_of_Thunder_supports_32_bit_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunder.exe Path:.
        /// </summary>
        public static string Thunder_exe_Path {
            get {
                return ResourceManager.GetString("Thunder_exe_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunder is not capable with POST method, and you may failed to download this file.
        ///Continue anyway?.
        /// </summary>
        public static string Thunder_is_not_capable_with_POST_method {
            get {
                return ResourceManager.GetString("Thunder_is_not_capable_with_POST_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThunderAgent.dll Path:.
        /// </summary>
        public static string ThunderAgent_dll_Path {
            get {
                return ResourceManager.GetString("ThunderAgent_dll_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Fix it!.
        /// </summary>
        public static string Try_Fix {
            get {
                return ResourceManager.GetString("Try_Fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome ThunderCross.
        /// </summary>
        public static string Welcome_ThunderCross {
            get {
                return ResourceManager.GetString("Welcome_ThunderCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should ThunderCross do with this file?.
        /// </summary>
        public static string What_should_ThunderCross_do_with_this_file {
            get {
                return ResourceManager.GetString("What_should_ThunderCross_do_with_this_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which is: .
        /// </summary>
        public static string Which_is {
            get {
                return ResourceManager.GetString("Which_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have choosen to open:.
        /// </summary>
        public static string You_have_choosen_to_open {
            get {
                return ResourceManager.GetString("You_have_choosen_to_open", resourceCulture);
            }
        }
    }
}
